version: '3.4'

services:
  contactreportdb:
    container_name: contactreportdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ContactReportDB
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@contact.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  contactapi:
    container_name: contactapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=contactreportdb;Port=5432;Database=ContactReportDB;User Id=admin;Password=admin1234;"
    depends_on:
     - contactreportdb
    ports:
      - "7000:80"

  reportapi:
    container_name: reportapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=contactreportdb;Port=5432;Database=ContactReportDB;User Id=admin;Password=admin1234;"
    depends_on:
     - contactreportdb
    ports:
      - "7001:80"

networks:
  rabbitmq_go_net:
    driver: bridge
